### ISSUE TITLE
Stack still deploys even when there is a build failure

### ISSUE THREAD

**Issue by s-fletcher** [faceteer/cdk#32]
<img width="1009" alt="Screen Shot 2022-07-14 at 12 14 41 AM" src="https://user-images.githubusercontent.com/11020347/178904517-28f6cbaf-fdb9-4ee5-8f83-18688f9705b4.png">

## Behavior

If some handler fails to be built, the stack will still be deployed to AWS and ultimately delete the api handler and its endpoint.

## Expected behavior

The entire deploy process should fail and no new updates should go into the cloud.

**Comment by SeriousBug** [comment]
This actually has been fixed with #42 

Deployments will now abort if the build for a handler failed.
